import "./globals.css";
import styles from "./layout.module.css";
import logo from "./logo.svg";
import clsx from "clsx";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Image from "next/image";
import localFont from "next/font/local";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

const materialSymbols = localFont({
  variable: "--font-family-symbols", // Variable name (to reference after in CSS/styles)
  style: "normal",
  src: "../node_modules/material-symbols/material-symbols-rounded.woff2", // This is a reference to woff2 file from NPM package "material-symbols"
  display: "block",
  weight: "100 700",
});

export const metadata: Metadata = {
  title: "Antes onboarding",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={clsx(inter.className, styles.body, materialSymbols.variable)}
      >
        <header className={styles.header}>
          <Image src={logo} alt="Antes Logo" height={24}></Image>
          <div className={styles.cornerSquare}></div>
        </header>
        <div className={styles.wrapper}>
          <div className={styles.container}>{children}</div>
          <nav className={styles.nav}>
            <ul className={styles.list}>
              <li className={styles.listItem}>
                <Link href={"/gebruiker"}>
                  <i className={clsx("symbol", styles.symbol)}>person</i>
                </Link>
              </li>
              <li className={styles.listItem}>
                <Link href={"/dashboard"}>
                  <i className={clsx("symbol", styles.symbol)}>dashboard</i>
                </Link>
              </li>
              <li className={styles.listItem}>
                <Link href={"/agenda"}>
                  <i className={clsx("symbol", styles.symbol)}>
                    calendar_month
                  </i>
                </Link>
              </li>
              <li className={styles.listItem}>
                <Link href={"/forum"}>
                  <i className={clsx("symbol", styles.symbol)}>forum</i>
                </Link>
              </li>
              <li className={styles.listItem}>
                <Link href={"/quiz"}>
                  <i className={clsx("symbol", styles.symbol)}>quiz</i>
                </Link>
              </li>
              <li className={styles.listItem}>
                <Link href={"/winkel"}>
                  <i className={clsx("symbol", styles.symbol)}>shopping_cart</i>
                </Link>
              </li>
              <li className={styles.listItem}>
                <Link href={"/instellingen"}>
                  <i className={clsx("symbol", styles.symbol)}>settings</i>
                </Link>
              </li>
            </ul>
          </nav>
        </div>
      </body>
    </html>
  );
}
